services:
  - type: web
    name: calculador-potodds-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    repo: https://github.com/devbot-agents/calculador-potodds-agent.git
    branch: main
    plan: free
